pre push hook

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -1,15 +1,32 @@
 #!/bin/sh
 
+# An example hook script to verify what is about to be pushed.  Called by "git
+# push" after it has checked the remote status, but before anything has been
+# pushed.  If this script exits with a non-zero status nothing will be pushed.
+#
+# This hook is called with the following parameters:
+#
+# $1 -- Name of the remote to which the push is being done
+# $2 -- URL to which the push is being done
+#
+# If pushing without using a named remote those arguments will be equal.
+#
+# Information about the commits which are being pushed is supplied as lines to
+# the standard input in the form:
+#
+#   <local ref> <local sha1> <remote ref> <remote sha1>
+#
+# This sample shows how to prevent push of commits where the log message starts
+# with "WIP" (work in progress).
 
-<?php
-echo "Running tests.. ";
-exec("vendor/bin/phpunit", $output, $returnCode);
-if ($returnCode !== 0) {
-  // Show full output
-  echo PHP_EOL . implode($output, PHP_EOL) . PHP_EOL;
-  echo "Aborting commit.." . PHP_EOL;
-  exit(1);
-}
-// Show summary (last line)
-echo array_pop($output) . PHP_EOL;
-exit(0);
+git diff --cached --name-only | while read FILE; do
+if [[ "$FILE" =~ ^.+(php|inc|module|install|test)$ ]]; then
+    echo "Running tests..."
+    cd "${0%/*}/.."
+    phpunit 1> /dev/null
+    if [ $? -ne 0 ]; then
+      echo -e "\e[1;31m\tUnit tests failed ! Aborting commit.\e[0m" >&2
+      exit 1;
+    fi
+fi
+done || exit $?
