pre push hook changes

diff --git a/hooks/pre-push b/hooks/pre-push
--- a/hooks/pre-push
+++ b/hooks/pre-push
@@ -19,6 +19,9 @@
 # This sample shows how to prevent push of commits where the log message starts
 # with "WIP" (work in progress).
 
+EXIT_CODE=0
+
+chmod +x ./.deploy/commands/*.sh
 
 # Sensiolabs Security Checker
 ./.deploy/commands/security_checker.sh || EXIT_CODE=1
@@ -34,6 +37,12 @@
 
 # PHP Mess Detector
 ./.deploy/commands/phpmd.sh || EXIT_CODE=1
+
+[ $EXIT_CODE -ne 0 ] &&
+echo -e "\n\t************************************************\n\t*  PRE-COMMIT HOOK FAILED (see reasons above)  *\n\t************************************************" ||
+echo -e "\n\t*********************************************\n\t*  PRE-COMMIT HOOK PASSED, ready to commit  *\n\t*********************************************"
+
+exit $EXIT_CODE
 
 
 exit 0
